#include<stdio.h>
#include<conio.h>
#include<graphics.h>
#include<alloc.h>
#define UP 1
#define DOWN 2
#define LEFT 3
#define RIGHT 4
#define PAUSE 5
int scancode();
void drawmaze();
void ghost();
void leval(int);
void mainmenu();
void main()
{
	int gdriver=DETECT,gmode,ch,x,y,direction,area,olx,oly,speed=5,ll=0,level=1,cs;
	char *up;
	char *down;
	char *left;
	char *right;
	char *pause;
	initgraph(&gdriver,&gmode,"d:/BGI");
	x=40;
	y=170;
	mainmenu();
	while(1)
	{
		ch=scancode();
		if(ch==2)
		{
			level=1;
			break;
		}
		else
		if(ch==3)
		{
			level=5;
			break;
		}
		else
		if(ch==4)
		{
			closegraph();
			exit();
		}
		else
		{
			continue;
		}
	}
	cleardevice();
	if(level==5)
	{
		closegraph();
		while(1)
		{
			clrscr();
			printf("enter a speed less than 13 to play:- ");
			scanf("%d",&cs);
			if(cs>13)
			{
				continue;
			}
			else
			{
				break;
			}
		}
		gdriver=DETECT;
		initgraph(&gdriver,&gmode,"d:\BGI");
	}

	setcolor(WHITE);
	line(x,y-15,x-10,y+10);
	line(x,y-15,x+10,y+10);
	line(x-10,y+10,x,y);
	line(x+10,y+10,x,y);
	setcolor(WHITE);
	area=imagesize(x-18,y-18,x+18,y+18);
	up=malloc(area);
	getimage(x-18,y-18,x+18,y+18,up);
	cleardevice();
	line(x+15,y,x-10,y-10);
	line(x+15,y,x-10,y+10);
	line(x,y,x-10,y-10);
	line(x,y,x-10,y+10);
	area=imagesize(x-18,y-18,x+18,y+18);
	right=malloc(area);
	getimage(x-18,y-18,x+18,y+18,right);
	cleardevice();
	line(x-15,y,x+10,y-10);
	line(x-15,y,x+10,y+10);
	line(x,y,x+10,y-10);
	line(x,y,x+10,y+10);
	area=imagesize(x-18,y-18,x+18,y+18);
	left=malloc(area);
	getimage(x-18,y-18,x+18,y+18,left);
	cleardevice();
	line(x,y+15,x-10,y-10);
	line(x,y+15,x+10,y-10);
	line(x,y,x-10,y-10);
	line(x,y,x+10,y-10);
	area=imagesize(x-18,y-18,x+18,y+18);
	down=malloc(area);
	getimage(x-18,y-18,x+18,y+18,down);
	cleardevice();
	circle(x,y,10);
	area=imagesize(x-18,y-18,x+18,y+18);
	pause=malloc(area);
	getimage(x-18,y-18,x+18,y+18,pause);
	direction=PAUSE;
	cleardevice();
	while(1)
	{
		setbkcolor(0);
		drawmaze();
		if(direction==UP)
		{
			putimage(x-18,y-18,up,COPY_PUT);
		}
		else
		if(direction==RIGHT)
		{
			putimage(x-18,y-18,left,COPY_PUT);
		}
		else
		if(direction==LEFT)
		{
			putimage(x-18,y-18,right,COPY_PUT);
		}
		else
		if(direction==DOWN)
		{
			putimage(x-18,y-18,down,COPY_PUT);
		}
		else
		if(direction==PAUSE)
		{
			putimage(x-18,y-18,pause,COPY_PUT);
		}


		if(olx>0-speed&&olx<0+speed&&oly>0-speed&&oly<getmaxy()+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>0-speed&&olx<getmaxx()+speed&&oly>0-speed&&oly<0+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>getmaxx()-speed&&olx<getmaxx()+speed&&oly>0-speed&&oly<getmaxy()+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>0-speed&&olx<getmaxx()+speed&&oly>getmaxy()-speed&&oly<getmaxy()+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>0-speed&&olx<190+speed&&oly>150-speed&&oly<150+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>0-speed&&olx<150+speed&&oly<190+speed&&oly>190-speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>190-speed&&olx<190+speed&&oly>150-speed&&oly<340+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>150-speed&&olx<150+speed&&oly>190-speed&&oly<380+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>190-speed&&olx<230+speed&&oly>340-speed&&oly<340+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>150-speed&&olx<270+speed&&oly>380-speed&&oly<380+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>430-speed&&olx<430+speed&&oly>290-speed&&oly<380+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>350-speed&&olx<430+speed&&oly>380-speed&&oly<380+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>230-speed&&olx<230+speed&&oly>50-speed&&oly<340+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>270-speed&&olx<270+speed&&oly>90-speed&&oly<380+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
		}
		else
		if(olx>230-speed&&olx<310+speed&&oly>50-speed&&oly<50+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>310-speed&&olx<310+speed&&oly>50-speed&&oly<getmaxy()-140+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>270-speed&&olx<350+speed&&oly>380-speed&&oly<380+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>350-speed&&olx<350+speed&&oly>160-speed&&oly<380+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>310-speed&&olx<390+speed&&oly>120-speed&&oly<120+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>390-speed&&olx<390+speed&&oly>120-speed&&oly<240+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>350-speed&&olx<430+speed&&oly>290-speed&&oly<290+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>430-speed&&olx<430+speed&&oly>250-speed&&oly<290+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>390-speed&&olx<470+speed&&oly>210-speed&&oly<210+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>470-speed&&olx<470+speed&&oly>210-speed&&oly<420+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>430-speed&&olx<470+speed&&oly>420-speed&&oly<420+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>430-speed&&olx<430+speed&&oly>420-speed&&oly<440+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>430-speed&&olx<470+speed&&oly>440-speed&&oly<440+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>470-speed&&olx<470+speed&&oly>420-speed&&oly<440+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>390-speed&&olx<390+speed&&oly>380-speed&&oly<getmaxy()+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>510-speed&&olx<510+speed&&oly>170-speed&&oly<getmaxy()+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>430-speed&&olx<510+speed&&oly>170-speed&&oly<170+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>430-speed&&olx<430+speed&&oly>80-speed&&oly<170+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>390-speed&&olx<390+speed&&oly>40-speed&&oly<120+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>390-speed&&olx<470+speed&&oly>40-speed&&oly<40+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>430-speed&&olx<510+speed&&oly>80-speed&&oly<80+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>510-speed&&olx<510+speed&&oly>0-speed&&oly<80+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>350-speed&&olx<350+speed&&oly>0-speed&&oly<80+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>40-speed&&olx<230+speed&&oly>50-speed&&oly<50+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>0-speed&&olx<80+speed&&oly>90-speed&&oly<90+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>130-speed&&olx<130+speed&&oly>50-speed&&oly<110+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>80-speed&&olx<80+speed&&oly>90-speed&&oly<150+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		else
		if(olx>130-speed&&olx<230+speed&&oly>110-speed&&oly<110+speed)
		{
			x=40;
			y=170;
			cleardevice();
			ll++;
			direction=PAUSE;
		}
		line(0,150,150,150);
		if(ll==3)
		{
			cleardevice();
			setbkcolor(BLUE);
			setfillstyle(SOLID_FILL,YELLOW);
			x=1;
			cleardevice();
			setfillstyle(SOLID_FILL,YELLOW);
			bar((getmaxx()/2)-220,(getmaxy()/2)-100,(getmaxx()/2)+210,(getmaxy()/2)+100);
			setfillstyle(SOLID_FILL,BLUE);
			setcolor(BLUE);
			settextstyle(COMPLEX_FONT,0,4);
			x=textwidth("OOPS! YOU LOST");
			outtextxy((getmaxx()/2)-(x/2),(getmaxy()/2)-90,"OOPS! YOU LOST");
			settextstyle(COMPLEX_FONT,0,1);
			x=textwidth("PRESS ANY KEY TO GO TO MAIN MENU:-");
			outtextxy((getmaxx()/2)-(x/2),(getmaxy()/2)-50,"PRESS ANY KEY TO GO TO MAIN MENU:-");
			getch();
			getch();
			mainmenu();
			while(1)
			{
				ch=scancode();
				if(ch==2)
				{
					level=1;
					direction=PAUSE;
					ll=0;
					x=40;
					y=170;
					cleardevice();
					break;
				}
				else
				if(ch==3)
				{
					closegraph();
					while(1)
					{
						clrscr();
						printf("enter the speed you want to play:- ");
						scanf("%d",&cs);
						if(cs>13)
						{
							continue;
						}
						else
						{
							break;
						}
					}
					gdriver=DETECT;
					initgraph(&gdriver,&gmode,"d:\BGI");
					level=5;
					speed=cs;
					x=40;
					y=170;
					direction=PAUSE;
					ll=0;
					cleardevice();
					break;
				}
				else
				if(ch==4)
				{
					closegraph();
					exit();
				}
				else
				{
					continue;
				}
			}
		}
		if(olx>191&&olx<229&&oly>300&&oly<339)
		{
			if(level==5)
			{
				ghost();
				cleardevice();
				setbkcolor(BLUE);
				setfillstyle(SOLID_FILL,YELLOW);
				cleardevice();
				setfillstyle(SOLID_FILL,YELLOW);
				bar((getmaxx()/2)-220,(getmaxy()/2)-100,(getmaxx()/2)+210,(getmaxy()/2)+100);
				setfillstyle(SOLID_FILL,BLUE);
				setcolor(BLUE);
				settextstyle(COMPLEX_FONT,0,4);
				x=textwidth("YOU WON");
				outtextxy((getmaxx()/2)-(x/2),(getmaxy()/2)-90,"YOU WON");
				settextstyle(COMPLEX_FONT,0,1);
				x=textwidth("PRESS ANY KEY TO GO TO MAIN MENU:-");
				outtextxy((getmaxx()/2)-(x/2),(getmaxy()/2)-50,"PRESS ANY KEY TO GO TO MAIN	 MENU:-");
				getch();
				mainmenu();
				while(1)
				{
					ch=scancode();
					if(ch==2)
					{
						level=1;
						direction=PAUSE;
						ll=0;
						x=40;
						y=170;
						cleardevice();
						break;
					}
					else
					if(ch==3)
					{
						closegraph();
						while(1)
						{
							clrscr();
							printf("enter a speed less than 13 o play:- ");
							scanf("%d",&cs);
							if(cs>13)
							{
								continue;
							}
							else
							{
								break;
							}
						}
						gdriver=DETECT;
						initgraph(&gdriver,&gmode,"d:\BGI");
						speed=cs;
						x=40;
						y=170;
						direction=PAUSE;
						level=5;
						ll=0;
						cleardevice();
						break;
					}
					else
					if(ch==4)
					{
						closegraph();
						exit();
					}
					else
					{
						continue;
					}
				}
			}
			else
			if(level==1||level==2||level==3)
			{
				level++;
				leval(level);
				ll=0;
				x=40;
				y=170;
				direction=PAUSE;
			}
		}
		if(level==1)
		{
			speed=5;
		}
		else
		if(level==2)
		{
			speed=6;
		}
		else
		if(level==3)
		{
			speed=7;
		}
		else
		if(level==4)
		{
			ghost();
			cleardevice();
			setbkcolor(BLUE);
			setfillstyle(SOLID_FILL,YELLOW);
			cleardevice();
			setfillstyle(SOLID_FILL,YELLOW);
			bar((getmaxx()/2)-220,(getmaxy()/2)-100,(getmaxx()/2)+210,(getmaxy()/2)+100);
			setfillstyle(SOLID_FILL,BLUE);
			setcolor(BLUE);
			settextstyle(COMPLEX_FONT,0,4);
			x=textwidth("YOU WON");
			outtextxy((getmaxx()/2)-(x/2),(getmaxy()/2)-90,"YOU WON");
			settextstyle(COMPLEX_FONT,0,1);
			x=textwidth("PRESS ANY KEY TO GO TO MAIN MENU:-");
			outtextxy((getmaxx()/2)-(x/2),(getmaxy()/2)-50,"PRESS ANY KEY TO GO TO MAIN MENU:-");
			getch();
			mainmenu();
			while(1)
			{
				ch=scancode();
				if(ch==2)
				{
					level=1;
					direction=PAUSE;
					ll=0;
					x=40;
					y=170;
					cleardevice();
					break;
				}
				else
				if(ch==3)
				{
					closegraph();
					while(1)
					{
						clrscr();
						printf("enter a speed less than 13 o play:- ");
						scanf("%d",&cs);
						if(cs>13)
						{
							continue;
						}
						else
						{
							break;
						}
					}
					gdriver=DETECT;
					initgraph(&gdriver,&gmode,"d:\BGI");
				}
				else
				if(ch==4)
				{
					closegraph();
					exit();
				}
				else
				{
					continue;
				}
			}

		}
		else
		if(level==5)
		{
			speed=cs;
		}
		outtextxy(190,getmaxy()-80,"LIVES LEFT:-");
		if(ll==0)
		{
			putimage(180-18,getmaxy()-60,right,OR_PUT);
			putimage(200-18,getmaxy()-60,right,OR_PUT);
			putimage(220-18,getmaxy()-60,right,OR_PUT);
		}
		else
		if(ll==1)
		{
			putimage(180-18,getmaxy()-60,right,OR_PUT);
			putimage(200-18,getmaxy()-60,right,OR_PUT);
		}
		else
		if(ll==2)
		{
			putimage(180-18,getmaxy()-60,right,OR_PUT);
		}
		drawmaze();
		if(kbhit())
		{
			ch=scancode();
			if(ch==72)/*up*/
			{
				direction=UP;
			}
			else
			if(ch==75)/*right*/
			{
				direction=RIGHT;
			}
			else
			if(ch==77)/*left*/
			{
				direction=LEFT;
			}
			else
			if(ch==80)/*down*/
			{
				direction=DOWN;
			}
			else
			if(ch==57)
			{
				direction=PAUSE;
			}
			else
			{
				mainmenu();
				while(1)
				{
					ch=scancode();
					if(ch==2)
					{
						level=1;
						direction=PAUSE;
						ll=0;
						x=40;
						y=170;
						cleardevice();
						break;
					}
					else
					if(ch==3)
					{
						closegraph();
						while(1)
						{
							clrscr();
							printf("enter a speed less than 13 o play:- ");
							scanf("%d",&cs);
							if(cs>13)
							{
								continue;
							}
							else
							{
								break;
							}
						}
						gdriver=DETECT;
						initgraph(&gdriver,&gmode,"d:\BGI");
						speed=cs;
						x=40;
						y=170;
						direction=PAUSE;
						level=5;
						ll=0;
						cleardevice();
						break;
					}
					else
					if(ch==4)
					{
						closegraph();
						exit();
					}
					else
					{
						continue;
					}
				}
			}
		}
			if(direction==UP)
			{
				y=y-speed;
				oly=y+speed;
			}
			else
			if(direction==DOWN)
			{
				y=y+speed;
				oly=y-speed;
			}
			else
			if(direction==RIGHT)
			{
				x=x-speed;
				olx=x+speed;
			}
			else
			if(direction==LEFT)
			{
				x=x+speed;
				olx=x-speed;
			}
			else
			if(direction==PAUSE)
			{}
			olx=x;
			oly=y;
	}
	closegraph();
}
int scancode()
{
	#include "dos.h"
	getch();
	{
	union REGS i, o ;
	while (!kbhit())
	;
	i.h.ah = 0 ;
	int86 ( 22, &i, &o ) ;
	return ( o.h.ah ) ;
	}
}
void drawmaze()
{
	setcolor(GREEN);
	line(0,150,190,150);
	line(0,190,150,190);
	line(190,150,190,340);
	line(150,190,150,380);
	line(190,340,230,340);
	line(150,380,270,380);
	line(230,340,230,50);
	line(270,380,270,90);
	line(230,50,310,50);
	line(310,50,310,getmaxy()-140);
	line(270,380,350,380);
	line(350,380,350,160);
	line(310,120,390,120);
	line(390,120,390,240);
	line(350,290,430,290);
	line(430,290,430,250);
	line(390,210,470,210);
	line(470,210,470,420);
	rectangle(350,290,430,380);
	line(470,420,430,420);
	line(430,420,430,440);
	line(430,440,470,440);
	line(470,440,470,420);
	line(390,380,390,getmaxy());
	line(510,getmaxy(),510,170);
	line(510,170,430,170);
	line(430,170,430,80);
	line(390,120,390,40);/*after this write if statements*/
	line(390,40,470,40);/*from here*/
	line(430,80,510,80);
	line(510,80,510,0);
	line(350,0,350,80);
	line(230,50,40,50);
	line(0,90,80,90);
	line(130,50,130,110);
	line(80,90,80,150);
	line(130,110,230,110);
	setcolor(BLUE);
	setfillstyle(SOLID_FILL,YELLOW);
	bar(191,300,229,339);
	setcolor(GREEN);
	line(150,190,150,getmaxy());
}
void leval(int level)
{
	int x;
	setcolor(BLUE);
	if(level==1)
	{
		setbkcolor(BLUE);
		setfillstyle(SOLID_FILL,YELLOW);
		cleardevice();
		setfillstyle(SOLID_FILL,YELLOW);
		bar((getmaxx()/2)-220,(getmaxy()/2)-100,(getmaxx()/2)+210,(getmaxy()/2)+100);
		setfillstyle(SOLID_FILL,BLUE);
		settextstyle(COMPLEX_FONT,0,3);
		x=textwidth("LEVEL ONE");
		outtextxy((getmaxx()/2)-(x/2),(getmaxy()/2)-90,"LEVEL ONE");
		settextstyle(COMPLEX_FONT,0,1);
		x=textwidth("SPEED:-X");
		outtextxy((getmaxx()/2)-(x/2),getmaxy()/2-60,"SPEED:-5");
		x=textwidth("PRESS ANY KEY TO CONTINUE!");
		outtextxy((getmaxx()/2)-(x/2),(getmaxy()/2)-30,"PRESS ANY KEY TO CONTINUE!");
		getch();
		cleardevice();
	}
	else
	if(level==2)
	{
		setbkcolor(BLUE);
		setfillstyle(SOLID_FILL,YELLOW);
		cleardevice();
		setfillstyle(SOLID_FILL,YELLOW);
		bar((getmaxx()/2)-220,(getmaxy()/2)-100,(getmaxx()/2)+210,(getmaxy()/2)+100);
		setfillstyle(SOLID_FILL,BLUE);
		settextstyle(COMPLEX_FONT,0,3);
		x=textwidth("LEVEL TWO");
		outtextxy((getmaxx()/2)-(x/2),(getmaxy()/2)-90,"LEVEL TWO");
		settextstyle(COMPLEX_FONT,0,1);
		x=textwidth("SPEED:-X");
		outtextxy((getmaxx()/2)-(x/2),getmaxy()/2-60,"SPEED:-6");
		x=textwidth("PRESS ANY KEY TO CONTINUE!");
		outtextxy((getmaxx()/2)-(x/2),(getmaxy()/2)-30,"PRESS ANY KEY TO CONTINUE!");
		getch();
		cleardevice();
	}
	else
	if(level==3)
	{
		setbkcolor(BLUE);
		setfillstyle(SOLID_FILL,YELLOW);
		cleardevice();
		setfillstyle(SOLID_FILL,YELLOW);
		bar((getmaxx()/2)-220,(getmaxy()/2)-100,(getmaxx()/2)+210,(getmaxy()/2)+100);
		setfillstyle(SOLID_FILL,BLUE);
		settextstyle(COMPLEX_FONT,0,3);
		x=textwidth("LEVEL THREE");
		outtextxy((getmaxx()/2)-(x/2),(getmaxy()/2)-90,"LEVEL THREE");
		settextstyle(COMPLEX_FONT,0,1);
		x=textwidth("SPEED:-X");
		outtextxy((getmaxx()/2)-(x/2),getmaxy()/2-60,"SPEED:-7");
		x=textwidth("PRESS ANY KEY TO CONTINUE!");
		outtextxy((getmaxx()/2)-(x/2),(getmaxy()/2)-30,"PRESS ANY KEY TO CONTINUE!");
		getch();
		cleardevice();
	}
}
void ghost()
{
	int x=200,y=200,k;
	int dx=1,dy=1,c=-1;
	cleardevice();
	setcolor(GREEN);
	circle(x,y,50); circle(x-20,y-10,10);
	circle(x+20,y-10,10); line(x+1,y-5,x,y+15);
	line(x,y+15,x+6,y+11); arc(x,y+5,240, 300, 30);
	line(x,y-80,x-50,y-19); line(x,y-80,x+50,y-19);
	k=getcolor();
	while(!kbhit())
	{
		setcolor(k);
		circle(x-25+(dx*c),y-10+(dy*c),2);
		circle(x+25+(dx*c*-1),y-10+(dy*c),2);
		setcolor(0);
		circle(x-25+(dx*c),y-10+(dy*c),2);
		circle(x+25+(dx*c*-1),y-10+(dy*c),2);
		c=c*-1;
	}
	getch();
}
void mainmenu()
{
	int tw;
	cleardevice();
	setbkcolor(BLUE);
	setfillstyle(SOLID_FILL,YELLOW);
	cleardevice();
	setfillstyle(SOLID_FILL,YELLOW);
	bar((getmaxx()/2)-245,(getmaxy()/2)-110,(getmaxx()/2)+245,(getmaxy()/2)+110);
	setfillstyle(SOLID_FILL,BLUE);
	settextstyle(COMPLEX_FONT,0,3);
	setcolor(RED);
	tw=textwidth("FAST AND FURIOUS");
	outtextxy((getmaxx()/2)-(tw/2),(getmaxy()/2)-100,"FAST AN");
	setcolor(RED);
	outtextxy((getmaxx()/2)-(tw/2),(getmaxy()/2)-100,"        D FURIOUS");
	settextstyle(COMPLEX_FONT,0,1);
	setcolor(BLUE);
	tw=textwidth("WHAT WOULD YOU LIKE TO DO?");
	outtextxy((getmaxx()/2)-235,(getmaxy()/2)-60,"WHAT WOULD YOU LIKE TO DO?");
	outtextxy((getmaxx()/2)-235,(getmaxy()/2)-24,"1>PLAY IN LEVEL MODE");
	outtextxy((getmaxx()/2)-235,(getmaxy()/2)-6,"2>PLAY IN SPEED COSTUMIZATION MODE");
	outtextxy((getmaxx()/2)-235,(getmaxy()/2)+12,"3>EXIT");
	tw=textwidth("LAKSHYA A AGRAWAL");
	setcolor(RED);
	outtextxy((getmaxx()/2)+(235-(tw)),(getmaxy()/2)+40,"PROGRAMMED BY:-");
	outtextxy((getmaxx()/2)+(235-tw),(getmaxy()/2)+60,"LAKSHYA A AGRAWAL");
	outtextxy((getmaxx()/2)+(235-tw),(getmaxy()/2)+80,"CLASS:-8th");
}







